language: en

pipeline:
 - name: WhitespaceTokenizer
 - name: RegexFeaturizer
   case_sensitive: false
 - name: LexicalSyntacticFeaturizer
 - name: CountVectorsFeaturizer
 - name: DIETClassifier
   epochs: 100
   constrain_similarities: true
   model_confidence: softmax
   split_entities_by_comma: True

policies:
 - name: MemoizationPolicy
 - name: TEDPolicy
   max_history: 5
   epochs: 50
   constrain_similarities: true
 - name: RulePolicy